<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="homepage.css?v=1.0">
</head>
<body>      
            <nav class="navbar">
                <div class="navdiv">
                        <div><a href="index.php"><img src="images/uvodni-logo.png"></a></div>
                    <ul>
                        <li>ŠPATNÉ PŘIHLAŠOVACÍ ÚDAJE</li>
                        <li><a href="login.php">PŘIHLÁŠENÍ</a></li>
                        <li><a href="products.phtml">PROHLÍŽENÍ PRODUKTŮ</a></li>
                    </ul>
                </div>
            </nav>
              
