<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="homepage.css">
</head>
<body>      
            <nav class="navbar">
                <div class="navdiv">
                        <div><a href="#"><img src="images/uvodni-logo.png"></a></div>
                    <ul>
                        <li><a href="login.phtml">PŘIHLÁŠENÍ</a></li>
                        <li><a href="registrace.phtml">REGISTRACE</a></li>
                        <li><a href="products.phtml">PROHLÍŽENÍ PRODUKTŮ</a></li>
                    </ul>
                </div>
            </nav>
                <div class="Message">
                Pro prohlížení objednávek se prosím přihlašte.
                </div>
            

                <div class="podpis">
                &copy Adam Mihok 2025
                </div>
</body>
</html>