<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="login.css">
</head>
<body>
    <nav>
        <ul>
            <li><a href="homepage.phtml">Domovská stránka</a></li>
            <li>Prohlížení produktů</li>
        </ul>
    </nav>
    <div class="hlavicka">
        <h1>VÍTEJTE</h1>

        <form class="formular" method="POST">
            <input type="text" placeholder="Uživatelské jméno" required>
            <input type="password" placeholder="Heslo" required>
            <a href="#">Zapomněli jste heslo?</a>
            <a href="#">Nemáte učet?</a>
            <button name="prihlaseni">Přihlásit se</button>
        </form>
    </div>

    <div style="color:white">
         &copy Adam Mihok 2025
    </div>
    
</body>
</html>