<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="login.css?v=1.0">
</head>
<body>
    <div class="hlavicka">
        <h1>VÍTEJTE</h1>

        <form class="formular" method="POST">
            <input type="text" placeholder="Uživatelské jméno" required>
            <input type="password" placeholder="Heslo" required>
            <a href="#">Zapomněli jste heslo?</a>
            <a href="#">Nemáte učet?</a>
            <button name="prihlaseni">Přihlásit se</button>
        </form>
    </div>
</body>
</html>