<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="login.css?v=1.0">
</head>
<body>
    <div class="hlavicka">
        <h1>Přidání produktu</h1>
        <form class="formular" method="POST">
            <label for="nazev">Název produktu</label>
            <input type="text" placeholder="rohlik" name="nazev">

             <label for="cena">Cena (kč)</label>
                <input type="number" placeholder="max 1000 (kc) "style="width:150px" min="1" max="1000" name="cena">

             <label for="hmotnost">Hmotnost</label>
             <input type="text" placeholder="500g" name="hmotnost" style="width:50px">

             <label for="arrival">Doba doručení</label>
             <input type="number" placeholder="max 30 (dní)" style="width:150px"min="1", max="30"name="arrival">
            
             <button name="addProduct">Přidat produkt</button>
        </form>
    </div>
</body>
</html>