-- MySQL Script generated by MySQL Workbench
-- Sun May 18 16:33:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `uzivatelske_jmeno` VARCHAR(50) NOT NULL,
  `heslo` VARCHAR(40) NOT NULL,
  `tel_cislo` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(50) NOT NULL,
  `psc` INT NOT NULL,
  `is_admin` INT NULL,
  PRIMARY KEY (`uzivatelske_jmeno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produkty` (
  `kod_produktu` INT NOT NULL AUTO_INCREMENT,
  `nazev_produktu` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  `hmotnost` INT NOT NULL,
  `doba_doruceni` INT NOT NULL,
  PRIMARY KEY (`kod_produktu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objednavky` (
  `kod_objednavky` INT NOT NULL AUTO_INCREMENT,
  `nazev_objednavky` VARCHAR(45) NOT NULL,
  `stav_objednavky` VARCHAR(45) NOT NULL,
  `cas_vytvoreni` DATETIME NOT NULL,
  `produkty_kod_produktu` INT NOT NULL,
  PRIMARY KEY (`kod_objednavky`),
  INDEX `fk_objednavky_produkty_idx` (`produkty_kod_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_objednavky_produkty`
    FOREIGN KEY (`produkty_kod_produktu`)
    REFERENCES `mydb`.`produkty` (`kod_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recenze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recenze` (
  `id_recenze` INT NOT NULL AUTO_INCREMENT,
  `popis` VARCHAR(100) NOT NULL,
  `pocet_hvezd` INT NOT NULL,
  `koupim_priste` VARCHAR(3) NOT NULL,
  `uzivatelske_jmeno` VARCHAR(45) NULL,
  `users_uzivatelske_jmeno` VARCHAR(50) NOT NULL,
  `objednavky_kod_objednavky` INT NOT NULL,
  PRIMARY KEY (`id_recenze`, `objednavky_kod_objednavky`),
  INDEX `fk_recenze_users1_idx` (`users_uzivatelske_jmeno` ASC) VISIBLE,
  INDEX `fk_recenze_objednavky1_idx` (`objednavky_kod_objednavky` ASC) VISIBLE,
  CONSTRAINT `fk_recenze_users1`
    FOREIGN KEY (`users_uzivatelske_jmeno`)
    REFERENCES `mydb`.`users` (`uzivatelske_jmeno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recenze_objednavky1`
    FOREIGN KEY (`objednavky_kod_objednavky`)
    REFERENCES `mydb`.`objednavky` (`kod_objednavky`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
