<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="homepage.css?v=1.0">
</head>
<body>      
            <nav class="navbar">
                <div class="navdiv">
                        <div><a href="index.php"><img src="images/uvodni-logo.png"></a></div>
                    <ul>
                        <li><?php 
                            
                            if($user["is_admin"]===1){
                            echo "Jste prihlasen jako ". $user["uzivatelske_jmeno"];
                            }elseif($user["is_admin"]===2)
                            echo "<p style='color:red;'> Jste prihlasen jako " . $user["uzivatelske_jmeno"]; "</p>" 
                                
                                    ?></li>
                        
                        <li><?php
                        if($user["is_admin"]===1){
                            echo "<a href='showproducts.php'>PROHLÍŽENÍ PRODUKTŮ</a></li>";
                        }elseif($user["is_admin"]===2){
                            echo "<li><a href='showproducts.php'>EDITACE PRODUKTŮ</a></li>";
                            echo "        ";
                            echo "<li><a href='products.php'>PŘIDÁNÍ PRODUKTŮ</a></li>";
                        }
                        
                        ?>
                        <li><a href="logout.php">ODHLÁŠENÍ</a></li>
                    </ul>
                </div>
            </nav>
              
